config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root "pets#index"

  resources :pets, only: [:index, :show, :new, :create, :destroy]

  resources :bookings, only: [:index, :create, :update, :destroy, :show, :new] do
    resources :reviews, only: [:new, :create, :show]
  end

  resources :reviews, only: [:destroy]

  get "dashboard", to: "dashboards#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pet
  belongs_to :user

  has_one :review, dependent: :destroy
end

app/models/pet.rb
class Pet < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_name_and_breed_and_description,
  against: [ :name, :breed, :description ],
  using: {
    tsearch: { prefix: true }
  }

  has_many :bookings, dependent: :destroy
  belongs_to :user

  has_one_attached :photo

  validates :name, :breed, :description, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :comment, :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :pets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:destroy]
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def show
    @booking = Booking.find(params[:id])
    @pet = @booking.pet
    @booking = Booking.new
  end

  def index
    @my_bookings = policy_scope(Booking)
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path, notice: 'You dont like the pet anymore!.'
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :template, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = current_user.bookings.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :pet_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def show
    @my_pets = current_user.pets
    @my_bookings = current_user.bookings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @pet = Pet.find(params[:id])
    authorize @pet
    pet_for_marker = Pet.where(id: params[:id])
    @booking = Booking.new
    @pets = Pet.all
    @markers = pet_for_marker.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {pet: pet})
      }
    end
  end

  def index
    @pets = policy_scope(Pet)
    if params[:query].present?
      @pets = Pet.search_by_name_and_breed_and_description(params[:query])
    end

    @markers = @pets.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude
      }
    end

  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    authorize @pet


    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    authorize @pet
    @pet.destroy
    redirect_to dashboard_path, notice: 'Pet passed away.'
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :breed, :description, :address, :image_url, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: %i[new create]
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating, :booking_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container" id="booking-form-container">
  <%= simple_form_for [booking], url: bookings_path(booking), html: { method: :post } do |f| %>
    <div class="w-100">
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.hidden_field :pet_id, value: params[:id] %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="d-flex w-100">
        <%= f.submit "Book me", class: "btn btn-primary w-100" %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="row">
  <% @my_bookings.each do |booking| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <%= image_tag booking.pet.image_url, class: "card-img-top", alt: booking.pet.name %>
        <div class="card-body">
          <h5 class="card-title"><%= booking.pet.name %></h5>
          <p class="card-text"><%= link_to 'See your status', booking_path(booking), class: 'btn btn-primary' %></p>
          <p class="card-text"><%= link_to 'Add a review', new_booking_review_path(booking), class: 'btn btn-primary' %></p>
          <p class="card-text"><%= link_to 'Delete', booking_path(booking), data: {turbo_method: :delete, confirm: 'Are you sure?'}, class: 'btn btn-danger' %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%= render "form", booking: @booking%>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="card-show d-flex">
        <%= image_tag "rabbit-charlie", width: 400 %>
        <div class="card-info d-flex flex-column justify-content-between w-100">
          <div class="info d-flex flex-column shrink">
            <h1>
              <%= @pet.name %>
            </h1>
            <small style="color:grey">
              <%= @pet.breed %> <br>
            </small>
            <small>
              <%= @pet.address %>
              <%= @pet.description %>
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_mybookings.html.erb
<div class="d-flex flex-column rounded-5 showcard">
          <div class="ps-4 py-3 border-bottom-custom">
            <strong> WELCOME !</strong></div>
            <div class="d-flex showcard-row border-bottom-custom">
              <div class="d-flex flex-column justify-content-between">
                <div class="ps-4 py-3 border-bottom-custom">
                  <strong> MY BOOKINGS </strong></div>
                    <% @my_bookings.each do |booking| %>

                      <div class="card-my-bookings d-flex">
                        <div>
                          <% if booking.pet.image_url.nil? %>
                            <%= cl_image_tag booking.pet.photo.key, class: "img-my-bookings" %>
                          <% else %>
                            <%= image_tag booking.pet.image_url, class: "img-my-bookings" %>
                          <% end %>
                        </div>

                        <div class="info-my-bookings mx-3 border-bottom-custom w-100">
                          <h2><%= booking.pet.name %></h2>
                          <p><%= booking.pet.breed %></p>

                        <button class="m-4 btn btn-outline-dark showcard-form-button d-flex px-4">
                          <div class="d-flex align-items-center">
                          <p class="my-0"> <%= link_to "ADD A REVIEW", new_booking_review_path(booking) %> </p></div></button>
                          </div>
                      <%= link_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, data: {turbo_method: :delete, confirm: 'Are you sure?'}, class: 'btn btn-danger' %>

                        </div>
                      </div>

                      </div>
                    <% end %>
                </div>
              </div>
            </div>
        </div>


      </div>
    </div>


















        <div>
          <% @my_pets.each do |pet| %>
            <%= link_to pet_path(pet), class: "pet-card" do %>

              <% if pet.image_url.nil? %>
                <%= cl_image_tag pet.photo.key, class: "pet-image"%>
              <% else %>
                <%= image_tag pet.image_url, class: "pet-image" %>
              <% end %>

              <div class="pet-text">
                <h2><%= pet.name %></h2>
                <p><%= pet.breed %></p>
              </div>
               <div>
                <a>
                  <%= link_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, data: {turbo_method: :delete, confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
                </a>
              </div>
            <% end %>
          <% end %>

        </div>

    </div>

  </div>

</div>

app/views/dashboards/extras.html.erb
<div class="row">
  <% @my_bookings.each do |booking| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <%= image_tag booking.pet.image_url, class: "card-img-top", alt: booking.pet.name %>
        <div class="card-body">
          <h5 class="card-title"><%= booking.pet.name %></h5>
          <p class="card-text"><%= link_to 'See your status', booking_path(booking), class: 'btn btn-primary' %></p>
          <p class="card-text"><%= link_to 'Add a review', new_booking_review_path(booking), class: 'btn btn-primary' %></p>
          <p class="card-text"><%= link_to 'Delete', booking_path(booking), data: {turbo_method: :delete, confirm: 'Are you sure?'}, class: 'btn btn-danger' %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <% @my_pets.each do |pet| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <%= image_tag pet.image_url, class: "card-img-top", alt: pet.name %>
        <div class="card-body">
          <h5 class="card-title"><%= pet.name %></h5>
        </div>
      </div>
    </div>
  <% end %>
</div>

        <div class="container">
<div class="d-flex flex-column rounded-5 showcard">
  <div class="ps-4 py-3 border-bottom-custom">
    <span><%= @pet.name %></span></div>
  <div class="d-flex showcard-row border-bottom-custom">
    <div class="d-flex flex-column justify-content-between">
    <div class="ps-4 py-3">
      <% breed_name = @pet.breed.downcase %>
      <% if ['a', 'e', 'i', 'o', 'u'].include?(breed_name[0]) %>
      I am an <%= breed_name %> and this is where I live:
      <% else %>
      I am a <%= breed_name %> and this is where I live:
      <% end %><br>
      <%= @pet.address %> <br><br>
      This is what they say about me:<br>
      <%= @pet.description %></div>
      <a href="#" class="m-4 btn btn-outline-dark w-25 showcard-form-button ">BOOK ME</a>
    </div>
    <div><%= image_tag @pet.image_url, width: 400 %></div>
  </div>

  <div class="ps-4 py-3 border-bottom-custom"><span>Reviews</span><br>
  <% if @pet.bookings.empty? %>
          <span>no reviews</span>
        <% else %>
          <% @pet.bookings.each do |booking| %>
           <% next if booking.review.nil? %>
            <%= render "reviews/card", review: booking.review %>
          <% end %>
        <% end %></div>
  <div class="ps-4 py-3"><span>You can find me here:</span></div>
  <div><div class="ps-4 py-3 overflow-hidden" style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div></div>
</div>
</div>

app/views/dashboards/show.html.erb
<div class="container">
  <div class="row">
    <div id= "menu" class="col-3">
      <strong>MENU</strong>


        <button class="dashboard-button d-flex">
          <div class="d-flex align-items-center">
            <i class="fa-solid fa-calendar mx-2"></i><p class="my-0">MY BOOKINGS</p>
          </div>
        </button>


        <button class="dashboard-button d-flex">
          <div class="d-flex align-items-center">
            <i class="fa-solid fa-paw mx-2"></i><p class="my-0">MY PETS</p>
          </div>
        </button>


        <button class="dashboard-button d-flex">
          <div class="d-flex align-items-center">
            <i class="fa-solid fa-message mx-2"></i><p class="my-0"> <%= link_to "ADD A NEW PET", new_pet_path, style: "color: black;" %> </p>
          </div>
        </button>


      <br>
      <p>Account & Profile</p>

      <strong id="booking-navbar"> <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete} %></strong>
    </div>

    <div id="bookings" class="col-9">
      <div class="container">
        <div class="d-flex flex-column rounded-5 showcard">
          <div class="ps-4 py-3 border-bottom-custom">
            <strong> WELCOME !</strong>
          </div>

          <div class="ps-4 py-3 border-bottom-custom">
            <strong> MY BOOKINGS </strong>
          </div>

          <div class="border-bottom-custom">
            <% @my_bookings.each do |booking| %>
              <div class="card-my-bookings d-flex border-bottom-custom">
                  <div>
                    <% if booking.pet.image_url.nil? %>
                      <%= cl_image_tag booking.pet.photo.key, class: "img-my-bookings" %>
                    <% else %>
                      <%= image_tag booking.pet.image_url, class: "img-my-bookings" %>
                    <% end %>
                  </div>

                <div class="info-my-bookings m-3">
                  <h2><%= booking.pet.name %></h2>
                  <p><%= booking.pet.breed %></p>

                  <div class="inside d-flex justify-content-between align-items-center">
                    <button class="m-4 btn btn-dark showcard-form-button d-flex px-4">
                      <div class="d-flex align-items-center">
                        <p class="my-0"> <%= link_to "ADD A REVIEW", new_booking_review_path(booking) %> </p>
                      </div>
                    </button>

                    <%= link_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, booking_path(booking), data: {turbo_method: :delete, confirm: 'Are you sure?'}, class: 'btn' %>

                  </div>

                </div>

              </div>
            <% end %>

          </div>

          <div class="ps-4 py-3 border-bottom-custom">
            <strong> MY PETS </strong>
          </div>
          <div class="border-bottom-custom">
            <% @my_pets.each do |pet| %>

              <div class="card-my-bookings d-flex border-bottom-custom">
                  <div>
                    <% if pet.image_url.nil? %>
                      <%= cl_image_tag pet.photo.key, class: "img-my-bookings" %>
                    <% else %>
                      <%= image_tag pet.image_url, class: "img-my-bookings" %>
                    <% end %>
                  </div>

                <div class="info-my-bookings m-3">
                  <h2><%= pet.name %></h2>
                  <p><%= pet.breed %></p>

                  <div class="inside d-flex justify-content-between align-items-center">

                    <%= link_to '<i class="fa-regular fa-trash-can"></i>'.html_safe, pet_path(pet), data: {turbo_method: :delete, confirm: 'Are you sure?'}, class: 'btn' %>

                  </div>

                </div>

              </div>
            <% end %>
          </div>


        </div>
      </div>

    </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmoPet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  </head>

  <body>
  <div class="page-container">
  <div class="navbar-container"><%= render "components/navbar" %></div>
  <div class="content-container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  <div class="footer-container"><%= render "components/footer" %></div>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello</h1>

app/views/pets/_form.html.erb
<div>
  <%= link_to '<i class="fa-solid fa-arrow-left-long"></i>'.html_safe, dashboard_path %>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1>New Pet</h1>
      <%= form_with(model: @pet, url: pets_path, method: :post) do |form| %>
        <div class="form__input">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form__input" %>
        </div>
        <div class="form__input">
          <%= form.label :breed %>
          <%= form.text_field :breed, class: "form__input" %>
        </div>
        <div class="form__input">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form__input" %>
        </div>
        <div class="form__input">
          <%= form.label :address %>
          <%= form.text_area :address, class: "form__input" %>
        </div>
        <div class="form__input">
          <%= form.label :image_url %>
          <%= form.text_field :image_url, class: "form__input" %>
        </div>
        <div class="actions">
          <%= form.submit "CREATE PET", class:"m-4 btn btn-outline-dark w-25 showcard-form-button" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>

app/views/pets/_info_window.html.erb
<h2><%= pet.name %></h2>
<p><%= pet.address %></p>

app/views/pets/index.html.erb
 <div class="container-main">
  <div class="d-flex flex-column justify-content-left caption">
    Discover, Connect, and Book:<br>
Find Your Ideal Pet Companion with Ease
    <%= form_with url: pets_path, method: :get, class: "search__container" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "search__input",
            placeholder: "Search for a pet",
            autocomplete: "off"
        %>
    <% end %>
    <button class="map-button" onclick="scrollToMap()">...or take me to map</button>
  </div>
</div>
  <div class="pet-container">
    <% @pets.each do |pet| %>
      <%= link_to pet_path(pet), class: "pet-card" do %>
        <% if pet.image_url.nil? %>
          <%= cl_image_tag pet.photo.key, class: "pet-image"%>

        <% else %>

          <%= image_tag pet.image_url, class: "pet-image" %>

        <% end %>
        <div class="pet-text">
          <h2><%= pet.name %></h2>
          <p><%= pet.breed %></p>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="my-3" style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

<script>
  function scrollToMap() {
    const mapSection = document.querySelector('.my-3');
    const yOffset = mapSection.getBoundingClientRect().top + window.scrollY;
    window.scrollTo({ top: yOffset, behavior: 'smooth' });
  }
</script>

app/views/pets/new.html.erb
<div class="container">
  <div class="d-flex flex-column rounded-5 showcard">
    <div class="ps-4 py-3">
      <h1>New Pet</h1>
      <%= form_with(model: @pet, url: pets_path, method: :post, data: {turbo: false}) do |form| %>
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :breed %>
          <%= form.text_field :breed, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :address %>
          <%= form.text_field :address, class: "form-control" %>
        </div>

        <%= form.hidden_field :user_id, value: current_user.id %>

        <div class="form-group">
          <%= form.label :photo %>
          <%= form.file_field :photo, class: "form-control" %>
        </div>

        <div class="actions">
          <%= form.submit "CREATE PET", class:"m-4 btn btn-outline-dark w-25 showcard-form-button" %>
        </div>
      <% end %>
      <div>
        <%= link_to '<i class="fa-solid fa-arrow-left-long"></i>'.html_safe, dashboard_path %>
      </div>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container">
  <div>
  <%= link_to '<i class="fa-solid fa-arrow-left-long display-4"></i>'.html_safe, root_path %>
</div>

<div class="d-flex flex-column rounded-5 showcard">
  <div class="ps-4 py-3 border-bottom-custom">
    <span><%= @pet.name %></span></div>

  <div class="d-flex showcard-row border-bottom-custom justify-content-between
  ">
    <div class="d-flex flex-column justify-content-between">
    <div class="ps-4 py-3">
      <% breed_name = @pet.breed.downcase %>
      <% if ['a', 'e', 'i', 'o', 'u'].include?(breed_name[0]) %>
      I am an <%= breed_name %> and this is where I live:
      <% else %>
      I am a <%= breed_name %> and this is where I live:
      <% end %><br>
      <%= @pet.address %> <br><br>
      This is what they say about me:<br>
      <%= @pet.description %></div>
      <%= link_to new_booking_path %>
      <%=link_to "BOOK ME", new_booking_path, class:"m-4 btn btn-outline-dark w-50 showcard-form-button"%> </div>
     <div>
      <% if @pet.image_url.nil? %>
        <%= cl_image_tag @pet.photo.key, width: 400%>
      <% else %>
        <%= image_tag @pet.image_url, width: 400 %>
      <% end %>
    </div>
  </div>

  <div class="ps-4 py-3 border-bottom-custom"><span>Reviews</span><br>exit
  <% if @pet.bookings.empty? %>
          <span>no reviews</span>
        <% else %>
          <% @pet.bookings.each do |booking| %>
           <% next if booking.review.nil? %>
            <%= render "reviews/card", review: booking.review %>
          <% end %>
        <% end %></div>
  <div class="ps-4 py-3"><span>You can find me here:</span></div>
  <div><div class="ps-4 py-3 overflow-hidden" style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div></div>
</div>

<%= link_to "Kill my pet", pet_path(@pet), class: "m-4 btn btn-outline-dark w-25 showcard-delete-button", data: {turbo_method: :delete, confirm: 'Are you sure?'} if policy(@pet).destroy?  %>
</div>

app/views/reviews/_card.html.erb
<div class="card-reviews">
  <p class="text-secondary">user: <%= review.user_id %></p>
  <%= review.rating %><i class="fa-solid fa-star text-black"></i>
  <p class="px-2"><%= review.comment %></p>

</div>

app/views/reviews/new.html.erb
<div>
  <%= link_to '<i class="fa-solid fa-arrow-left-long"></i>'.html_safe, dashboard_path %>
</div>
<div class="row">
  <div class="col-6 m-auto">
    <h1>New review</h1>
    <%= simple_form_for [@booking, @review] do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating, label: 'Rating (0-5)', collection: 0..5 %>
      <%= f.hidden_field :booking_id, value: params[:id] %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "Go back", booking_path(@booking) %>

  </div>

</div>